# Generated by Django 5.1 on 2024-08-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[(1, 'Baixa'), (2, 'Media'), (3, 'Alta')], default=(1, 'Baixa'), max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('overdue', 'Atrasado'), ('defer', 'Adiado'), ('completed', 'Concluído')], default=('pending', 'Pendente'), max_length=20),
        ),
    ]
