# Generated by Django 5.1 on 2024-08-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('middle', 'Media'), ('high', 'Alta')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('overdue', 'Atrasado'), ('defer', 'Adiado'), ('completed', 'Concluído')], default='pending', max_length=20),
        ),
    ]
