# Generated by Django 5.1 on 2024-08-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_priority_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
